name: Generate Snake

on:
  schedule: 
      - cron: "0 0 * * *" # roda uma vez por dia
  workflow_dispatch: # permite rodar manualmente
  push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: manu-hostin
          outputs: dist/snake.svg

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
